# Generated by Django 2.1.5 on 2019-02-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [['can_view_post', 'Can view post'], ['hi', 'hi']]},
        ),
    ]
